#ifndef H_DEFINES_H
#define H_DEFINES_H

#define PIN_WATER_TEMPERATURE_SENSOR GPIO_NUM_4
#define WATER_TEMPERATURE_SENSOR_DS18B20

#define PIN_HEATING_RELAY GPIO_NUM_5
#define HEATING_DRIVER_PWM_RELAY

#endif